### ISSUE TITLE
Question: Humidity level

### ISSUE THREAD

**Issue by 350d** [neptunix/homebridge-trigger#1]
Hello! Can you please show an example about how to setup Homebridge to switch one of my smart plugs on and off based on humidity level value from one of my sensors? Thank you!

**Comment by neptunix** [comment]
Hi!
You don't need this plugin to trigger automations base on Humidity Level as it is a Default HomeKit value type.

I recommend you to install [Elgato Eve](https://itunes.apple.com/us/app/elgato-eve/id917695792?mt=8) app, and create a new trigger based on humidity value

**Comment by 350d** [comment]
I have Mi Temp/Humidity sensor here in my setup and I can see it in HomeKit App in devices/sensors list but can't find it in Automations tab. Is it should be there or this functionality only available in 3rd party apps like Elgato?

**Comment by neptunix** [comment]
Yes, you’ll find it in the Elgato App. Home app does not let you create such automations

**Comment by neptunix** [comment]
Hope it's resolved
